---
title: "Coding Challenge 3"
author: "Jae Wook Jung"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:  
    keep_md: true
    code_folding: hide
    toc: true
    toc_float: true
    fig_height: 6
    fig_width: 12
    fig_align: 'center'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE}
library(tidyverse)
```

```{r message=FALSE, warning=FALSE}
#The rio package will simplify reading in Excel files. We need the third sheet in the dataset, so sheet = "Full data" provides the needed code. 
#install.packages("rio")
my_data <- rio::import("https://www.rug.nl/ggdc/historicaldevelopment/maddison/data/mpd2020.xlsx",sheet = "Full data")
my_data <- na.omit(my_data)
my_data <- my_data %>% filter(year >= 1820)

#If the source site is down, you can also grab the data from a temporary repository created for this coding challenge. 
#my_data1 <- rio::import("https://byuimath.com/bmw/s21/mpd2020.xlsx",sheet = "Full data")
#View(my_data1)

#This line of code will read in the region table, which you'll need to assign each country to its appropriate region. 
my_region_table <- read_csv("https://byuimath.com/bmw/s21/my_region_table.csv")
```

```{r message=FALSE, warning=FALSE}
colnames(my_region_table)[2] <- "countrycode"
```

```{r message=FALSE, warning=FALSE}
world_data <- my_data %>% group_by(year) %>% summarise(gdppc = weighted.mean(gdppc, w = pop), pop = sum(pop), region = "World") %>% filter(year >= 1820)
```

```{r message=FALSE, warning=FALSE}
my_region_table$region <- stringr::str_replace(my_region_table$region, "Australia and New Zealand", "Western Offshoots")
my_region_table$region <- stringr::str_replace(my_region_table$region, "Northern America", "Western Offshoots")
my_region_table$region <- stringr::str_replace(my_region_table$region, "Eastern Asia", "East Asia")
my_region_table$region <- stringr::str_replace(my_region_table$region, "South-eastern Asia", "South and South-East Asia")
my_region_table$region <- stringr::str_replace(my_region_table$region, "Southern Asia", "South and South-East Asia")
my_region_table$region <- stringr::str_replace(my_region_table$region, "Latin America and the Caribbean", "Latin America")
my_region_table$region <- stringr::str_replace(my_region_table$region, "Sub-Saharan Africa", "Sub-Sahara Africa")
```

```{r message=FALSE, warning=FALSE}
my_data1 <- left_join(my_data, my_region_table %>% select(-country), by = "countrycode")

my_regional <- my_data1 %>% group_by(year, region) %>% summarise(gdppc = weighted.mean(gdppc, pop, na.rm = TRUE))

my_regional1 <- my_regional %>% filter(region %in% c("Western Offshoots", "Western Europe", "Eastern Europe", "Middle East", "East Asia", "Latin America", "South and South-East Asia", "Sub-Sahara Africa"))
```

```{r message=FALSE, warning=FALSE}
ggplot() +
  geom_point(my_regional1, mapping = aes(year, gdppc, color = region)) +
  geom_line(my_regional1, mapping = aes(year, gdppc, color = region)) +
  geom_point(world_data, mapping = aes(year, gdppc, color = region)) +
  geom_line(world_data, mapping = aes(year, gdppc, color = region)) +
  theme_bw() +
  ggrepel::geom_label_repel(aes(year, gdppc, label = region), data = my_regional1 %>% filter(year == 2018), nudge_x = -10, nudge_y = -2) +
  ggrepel::geom_label_repel(aes(year, gdppc, label = region), data = world_data %>% filter(year == 2018), nudge_x = 100, nudge_y = -2) +
  theme(legend.position = "none") +
  scale_x_continuous(NULL, expand = expansion(mult = c(0, 0.2)))
  
```

