---
title: "Task 16"
author: "Jae Wook Jung"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:  
    keep_md: true
    toc: true
    code_folding: hide
    toc_float: true
    fig_height: 6
    fig_width: 12
    fig_align: 'center'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(downloader)

download("http://scriptures.nephi.org/downloads/lds-scriptures.csv.zip", "temp.zip")
unzip("temp.zip")

scripture_data <- read_csv("lds-scriptures.csv",
                           col_types = cols(book_subtitle = col_character(),
                                            volume_subtitle = col_character()))

```

#### What is the average verse length (number of words) in the New Testament compared to the Book of Mormon?

```{r message=FALSE, warning=FALSE}
scripture_new_mor <- scripture_data %>% filter(volume_title == "New Testament" | volume_title == "Book of Mormon")
# scripture_new_mor$lengths <- str_count(scripture_new_mor$scripture_text, " ") + 1

scripture_new_mor$lengths <- str_count(scripture_new_mor$scripture_text, boundary("word"))

scripture_new_mor %>% group_by(volume_title) %>% summarise(`avg number of words` = mean(lengths))

```

#### How often is the word "Jesus" in the New Testament compared to the Book of Mormon?

```{r}
scripture_new_mor$Je <- str_count(scripture_new_mor$scripture_text, "Jesus")

scripture_new_mor %>% group_by(volume_title) %>% summarise(`number of Jesus` = sum(Je))

```

#### What does the distribution of verse word counts look like for each book in the Book of Mormon?

```{r}
ggplot(scripture_new_mor %>% filter(volume_title == "Book of Mormon"), aes(x = book_title, y = lengths, color = book_title)) +
  geom_boxplot() +
  labs(title = "Book of Mormon Each Book Verse Word Counts", x = "Book Title", y = "Number of Words") +
  theme_bw() +
  theme(legend.position = "none", axis.text.x = element_text(angle = 45, hjust = 1), panel.grid.major.x = element_blank())

```

